### ISSUE TITLE
new function to obtain a multi-class variable from a set of scGate models' pure/impure output

### ISSUE THREAD

**Issue by sjcarmona** [carmonalab/scGate#11]
After multiple scGate models have been evaluated (e.g. scGate_CD8T, scGate_Bcell):

                   scGate_CD8T      scGate_Bcell
    cell1                 Pure            Impure
    cell2               Impure              Pure
    cell3               Impure            Impure
    cell4                 Pure              Pure

Generate a new 'multi-class' variable (from all scGate* variables, or user-defined list,), eg

                   scGate_multiClass     
    cell1                CD8T
    cell2                Bcell   
    cell3                None  
    cell4                Multi

**Comment by mass-a** [comment]
Now implemented in dev version as `combine_scGate_multiclass`:

https://github.com/carmonalab/scGate/blob/dev/man/combine_scGate_multiclass.Rd
