### ISSUE TITLE
Use of pos.thr neg.thr

### ISSUE THREAD

**Issue by france-hub** [carmonalab/scGate#15]
Hello! Thanks again for this package!

I have a question on the scGate function. 
Here is the piece of code I use to gate on CD8 T cells trying to exclude CD4s and MAIT (sobj is my seurat object which are CD3+ T cells)

```
CD8 <- c("CD8A", "CD8B")
CD4 <- "CD4"
MAIT <- c("SLC4A10", "TRAV1-2")
mmCD8 <- scGate::gating_model(level=1, name="CD8T", signature = CD8)
mmCD8 <- scGate::gating_model(model=mmCD8, level=1, name="MAIT", signature = MAIT, negative=TRUE)
mmCD8 <- scGate::gating_model(model=mmCD8, level=1, name="CD4T", signature = CD4, negative=TRUE)
CD8sub <- scGate(sobj, model = mmCD8)
CD8sub <- subset(CD8sub, subset = `is.pure` == "Pure" )
```

After this if I run
`FeaturePlot(CD8sub, c("CD8A", "CD4")`
![features](https://user-images.githubusercontent.com/56587709/191003759-7e7426f2-fd9f-4844-8504-7aeb59d88c3c.png)

There are some areas that look like CD4+ (not much) and some areas that are CD8- (I can see one cluster CD8A- and it's also CD8B-) 

I guess I could try to increase the pos.thr argument, right? But how much should I increase the threshold? What are here your suggestions to get pure CD8s?

Thanks!
Francesco

**Comment by mass-a** [comment]
Hello Francesco,

perhaps you can visualize the UCell scores alongside the expression of individual genes: e.g.
```
FeaturePlot(CD8sub, c("CD8_UCell", "CD4_UCell")
```
This may help you identify better thresholds for filtering. One thing to keep in mind is that UCell scores are smoothed by their nearest neighbors, so even if a cell has low score for a given signature, but most of its neighbors are high, it may still pass through the filter (and the opposite).

It's true that there seems to be a cluster of CD8A- cells in your plots. One thing to check: how many genes are detected in your dataset (and in this cluster in particular)? By default UCell scores are calculated on the top ranking 1500 genes per cell, but if you have fewer than this number of detected genes, even lowly expressed genes may get non-zero scores. You could try to lower the `maxRank` parameter which controls this behavior.

Finally, the CD4 gene is often not very well detected in scRNA-seq. You may be able to increase the sensitivity of the gating model by adding some other genes to the CD4 signature. For instance we found CD40LG to be useful to purify CD4+ T cells, in combination with CD4.

I hope this helps,
-massimo
