### ISSUE TITLE
scGate & performance.metrics

### ISSUE THREAD

**Issue by denizff** [carmonalab/scGate#16]
Hi, 
I had two problems with scGate.
First, when using scGate with a SCT assay, I had the following warning : "The umi assay (RNA) is not present in the object. Cannot Compute additional residuals". I don't really know where the umi assays should be in the SCT assay. I coudnt solve the problem
Second, when using performance metrics, I had an integer overflow because of high integer values.
But when I did the operations myself as numerics, I didn't have any problems.

Best regards,

Deniz Fettahoglu

**Comment by denizff** [comment]
And thanks for making this package ! 

Best regards,

Deniz Fettahoglu

**Comment by mass-a** [comment]
Hello Deniz,

It looks like an issue with the SCT normalization, but it's hard to debug without seeing your code. Would you be able to provide a small example that reproduces these errors?

Best
-m
