### ISSUE TITLE
nn.idx with pre-calculated dimensionality reductions

### ISSUE THREAD

**Issue by dy-lin** [carmonalab/scGate#17]
I'm working with a DOGMA-seq dataset, a multimodal dataset with scATAC, scRNA, and scADT. 

I've conducted weighted nearest neighbour analysis as described here: https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html

```r
DOGMA <- FindMultiModalNeighbors(DOGMA, reduction.list = c("pca.rna","lsi.atac", "pca.adt"), dims.list = list(1:30, 2:30,1:30),  modality.weight.name = "DOGMA.weight")
DOGMA <- RunUMAP(DOGMA, nn.name = "weighted.nn", reduction.name = "umap.wnn", reduction.key = "wnnUMAP_")
DOGMA <- FindClusters(DOGMA, graph.name = "wsnn", algorithm = 3)
```

Then, using scGate:
```r
obj <- scGate(DOGMA, model = models.list, assay = "GeneActivity", reduction = "umap.wnn")
```

I get this error:
```
Error in filter_bymean(q, positive = pos.names, negative = neg.names,  : 
  trying to get slot "nn.idx" from an object of a basic class ("NULL") with no slots
```

The `weighted.nn` Neighbour object was used in the `RunUMAP()` command that generated the `umap.wnn`.
```
> DOGMA@reductions$umap.wnn
A dimensional reduction object with key wnnUMAP_ 
 Number of dimensions: 2 
 Projected dimensional reduction calculated:  FALSE 
 Jackstraw run: FALSE 
 Computed using assay: ADT 
> DOGMA@neighbors$weighted.nn
A Neighbor object containing the 20 nearest neighbors for 4802 cells
```

How I do specify the Neighbour class (https://github.com/mojaveazure/seurat-object/blob/master/R/neighbor.R) with the `nn.idx` slot from the pre-calculated dimensionality reduction?

**Comment by mass-a** [comment]
Hello and thanks for the bug report.

I see you are running scGate with `reduction = "wnn.umap"` but in your object it seems to be called `umap.wnn`. Can that be the issue?

-m

**Comment by dy-lin** [comment]
That should just be a copy paste error between different versions of the code, but I will double check.

**Comment by mass-a** [comment]
Thanks for clarifying.

You could try the development version of scGate, where we switched the nearest neighbor algorithm to `BiocNeighbors`. This is a simpler implementation and does away with Neighbor objects. For this you also need the latest `UCell` from Github (will also be available with the upcoming release of Bioconductor next week):
```r
remotes::install_github("carmonalab/UCell")
remotes::install_github("carmonalab/scGate", ref="dev")
```

If this doesn't work, perhaps you could share one of your multimodal datasets so I can try to reproduce the error?

Best
-massimo

**Comment by dy-lin** [comment]
I was able to reproduce the error using a public multimodal dataset: https://www.10xgenomics.com/resources/datasets/pbmc-from-a-healthy-donor-no-cell-sorting-3-k-1-standard-2-0-0

I have an `.rds` file with the Seurat object with the calculated dimensional reductions. Where should I send it?

In the meantime I will try the development version.

**Comment by mass-a** [comment]
Sorry it took this long to get back to you.
I got around to testing scGate on a multi-modal dataset after weighted nearest neighbour analysis using `FindMultiModalNeighbors`. I can confirm that the development version of scGate works if you specify a combined reduction, as in your example. Unfortunately that does require having R4.2 or higher, as it depends on packages in Bioconductor >=3.15; no easy way around that.

Best
-massimo
