### ISSUE TITLE
incomplete final line found by readTableHeader on HSPC_scGate_Model

### ISSUE THREAD

**Issue by bbimber** [carmonalab/scGate#31]
This is a small issue, but I believe HSPC_scGate_Model.tsv is throwing a warning b/c it has an incomplete line (dropping the trailing tab). I'm pretty sure you could use "utils::read.table(fill = TRUE)" to avoid this. Again, not a huge issue, but thought i would report it.

```
Warning ('test-scgate.R:101:3'): scGates runs on all
incomplete final line found by readTableHeader on '/tmp/RtmpId3W7Y/scGate_models-master/human/PBMC/HSPC_scGate_Model.tsv'
Backtrace:
    ▆
 1. └─RIRA::RunScGateWithDefaultModels(seuratObj, dropAmbiguousConsensusValues = TRUE) at test-scgate.R:101:3
 2.   └─RIRA::RunScGateForModels(...)
 3.     └─RIRA::RunScGate(...)
 4.       └─RIRA::GetScGateModel(model)
 5.         └─scGate::get_scGateDB(force_update = T, destination = modelDir)
 6.           └─scGate:::load.model.helper(model_path, verbose = verbose)
 7.             └─utils::read.table(file.path(models_path, f), sep = "\t", header = T)
 ```

**Comment by mass-a** [comment]
Thanks for reporting!

I don't think your proposed `utils::read.table(fill = TRUE)` would work, in fact it complains about the lack of a new line at the end of the file. But we can safely ignore (or suppress) the warning, it seems the tables are loaded correctly also when the .tsv does not end with a trailing new line.

**Comment by bbimber** [comment]
Yes, it does appear they're loaded correctly. suppressWarnings() would also work.
