### ISSUE TITLE
Logical operators

### ISSUE THREAD

**Issue by france-hub** [carmonalab/scGate#4]
Hello, 

Thank you for this great package. It's saving me a lot of time in annotating my subsets. The possibility of excluding some markers just adding the negative sign was a wonderful idea!

I was wondering if there is the chance of including logical operators in the signature argument i.e. "CD8A&KLRG1" if I want for example include all the KLRG1+ in the CD8 subset. 

Thank you very much

Francesco

**Comment by mass-a** [comment]
Hello Francesco,
one way of achieving a double subsetting is to set up a simple hierarchical model, e.g.
```
my.model <- scGate::gating_model(level=1, name="Cd8T", signature = c("CD8A","CD8B"))
my.model <- scGate::gating_model(model=my.model, level=2, name="SLEC", signature = c("KLRG1"))
my.model
```
```
  levels   use_as name signature
1 level1 positive CD8.T CD8A;CD8B
2 level2 positive SLEC     KLRG1
```
This model would first filter CD8 T cells, then gates KLRG1+ cells from the CD8 T subset. Does that make sense?

I like your suggestion of using logical operators – perhaps we could implement that as a shortcut for setting up a model like the one above.

Cheers,
-m

**Comment by france-hub** [comment]
Thanks! It makes sense

**Comment by NoemieL** [comment]
Hello,
Based on what you said earlier, I imagine a cell is considered as CD8 T cells if it expressed CD8A OR CD8B, right?

Cheers

**Comment by mass-a** [comment]
Hello Noemie,

a [UCell](https://github.com/carmonalab/UCell) score is calculated for each cell based on the combined ranking of all genes in a signature (CD8A+CD8B+ in the example above) and smoothed using the scores of neighbor cells. If this score is above the `pos.thr` threshold it will be considered as a "pure" cell for the target cell type. You can always inspect the distribution of these scores by looking at the meta.data of the resulting seurat object (the columns that end with "_UCell") and adjust signatures and thresholds accordingly.

Best
-m

**Comment by mass-a** [comment]
Ok I see!
you could try to add an alternative "positive" signature to the existing model, e.g.
```
#Get existing model for plasma cells
models.DB <- scGate::get_scGateDB()
plasma <- scGate_models_DB$human$generic$Plasma_cell

#Add alternative plasma cell definition
plasma.lambda <- c("level4","positive","Plasma_lambda","IGLC2;IGLC3;CD19-")
plasma <- rbind(plasma, plasma.lambda)

tail(plasma)
```

```
   levels   use_as          name                                            signature
15 level3 negative         Tcell                                   CD3D;CD3E;CD3G;CD2
16 level3 negative         Bcell                                MS4A1;BANK1;PAX5;CD19
17 level3 negative            NK KLRD1;NKG7;NCR1;FCGR3A;CD3D-;CD3E-;CD3G-;CD8A-;CD8B-
18 level4 positive   Plasma_cell                         IGKC;IGHG3;IGHG1;IGHA1;CD19-
19 level4 negative         Bcell                                MS4A1;BANK1;PAX5;CD19
20 level4 positive Plasma_lambda                                    IGLC2;IGLC3;CD19-
```

In this case you have two alternative definitions of plasma cells, and if either of them is positive it will pass the filter. Does it make sense?

I am sure you can improve these signatures for plasma cells with your expertise. If you find a model that works well, please let us know and we can update the repository of default scGate models!

Best,
-massimo

**Comment by NoemieL** [comment]
Thank you very much Massimo. I have couples more questions for you.

1. Do I need to add this "positive" signature at each levels (level1, 2, and 3) or just the last level is sufficient? 
2. Also if I want to keep the cells that have similar characteristics to B cells (since plasma cells derived from B cells).  Should I just removed the "negative" signatures of B cells from the object? or do you suggest something else?

Best

**Comment by mass-a** [comment]
>     1. Do I need to add this "positive" signature at each levels (level1, 2, and 3) or just the last level is sufficient?

Yes it's a good idea to have the signature for the target population at each level, that should ensure it will pass all gating levels. 
 
>     2. Also if I want to keep the cells that have similar characteristics to B cells (since plasma cells derived from B cells). Should I just removed the "negative" signatures of B cells from the object? or do you suggest something else?

You could remove the signatures for B cells from the negative set, or even explicitly set them as "positive" if you want to capture both B cells and plasma cells. If there are pan-B cells markers that you know of (i.e. genes that are both expressed in B cells and plasma cells) you could add those too. The structure of scGate models should allow you to experiment with different gating strategies depending on your purification goals.

Cheers,
-m
