### ISSUE TITLE
Error: irlba(A = t(x = object), nv = npcs, ...)

### ISSUE THREAD

**Issue by bbimber** [carmonalab/scGate#5]
Hello,

We're getting errors running scGate::scGate(), along the lines of:

Error in irlba(A = t(x = object), nv = npcs, ...) : 
max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

Are you familiar with anything like this? Does this indicate our input has too few cells or a rare cluster with too few cells? Thanks in advance for any help.

**Comment by bbimber** [comment]
Looking at your code, it seems like this might related to find.nn(). I also see that your default for min.cells is currently 30. for what reason we're using 10. I'll increase this and see if it helps.

**Comment by mass-a** [comment]
Hello,

could you share a small example that reproduces this error? this would help us debugging the problem.

Thanks,
-m

**Comment by bbimber** [comment]
@mass-a Thanks for following up. Sharing a minimal repro isnt all that easy; however, I think my second post (which I found right after reporting this) explains it. I dont know why our code was using min.cells=10 (I must have seen this is an scGate vignette). However, changing from min.cells=10 to min.cells=30, like your defaults, avoids the issue. Running PCA with too few cells is probably the culprit.

**Comment by mass-a** [comment]
As a little follow up – indeed, an error may occur if `min.cells` < `ndim` (both 30 by default), where the method attempts to perform PCA with more dimensions than there are cells. We will a parameter check to avoid this situation.

Thanks for reporting this.
-m
