### ISSUE TITLE
ArchRproject implementation

### ISSUE THREAD

**Issue by NoemieL** [carmonalab/scGate#6]
Hi,
Thank you for this nice package. I am analysis my scATACseq and matching scRNAseq data using ArchR. I would be interested to use your package on my ArchRproject but it is not implemented. Do you think it will be possible to implement this option? However what data do I need to extract from my ArchRproject to run scGate?

Thanks in advances for your help

**Comment by NoemieL** [comment]
Hello,

Thank you very much. I am working on multiple myeloma cells that are abnormal plasma cells. With my scRNA seq I could removed the non-PC. I did what you suggested for the matched scATACseq but in this cases all the cells are removed.  I increased the maxRank but did not change the results. Do you have any ideas of what to change?

Here is my code:
> ATAC_data=getMatrixFromProject(MM_T_whithout_doublets,useMatrix = "GeneScoreMatrix")
library(escape)
> ATAC_data=as(ATAC_data, "SingleCellExperiment") #get expression matrix as singleCellExperiment Object
> row.names(ATAC_data)=rowData(ATAC_data)$name
> assayNames(ATAC_data)[1]="counts"
> ATAC_data_seurat <- as.Seurat(ATAC_data, counts = "counts",data=NULL)

> apply(ATAC_data_seurat@meta.data[,c("nCount_originalexp","nFeature_originalexp")], MARGIN = 2, median)
nCount_originalexp nFeature_originalexp 
               10000                13716 

> ATAC_data_seurat2 <- scGate(ATAC_data_seurat, model = scGate_models_DB$human$generic$Plasma_cell, assay =DefaultAssay(ATAC_data_seurat),maxRank = 10000 )

Computing UCell scores for signatures...

Running scGate on level 1...
scGate: Detected 29277 non-pure cells at level 1
Running scGate on level 2...
scGate: Detected 18444 non-pure cells at level 2
Running scGate on level 3...
scGate: Detected 34656 non-pure cells at level 3
Running scGate on level 4...
scGate: Detected 11717 non-pure cells at level 4

### Detected a total of 94094 non-pure cells for selected signatures - 96.63% cells marked for removal (active.ident)

> summary(ATAC_data_seurat@assays$originalexp@counts["IGKC",])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    0.00    0.00    0.39    0.00   20.05 
> summary(ATAC_data_seurat@assays$originalexp@counts["IGHG3",])
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
 0.00000  0.00000  0.00000  0.04863  0.00000 22.14900 
> summary(ATAC_data_seurat@assays$originalexp@counts["IGLC1",])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.2907  0.0000 13.9510

I tried with another custom set of genes of myeloma genes and it looks better
model <- scGate::gating_model(name="MMcell.ATAC",signature = c("TNFRSF17","SDC1"))
ATAC_data_seurat2 <- scGate(data =ATAC_data_seurat, model = model, assay = DefaultAssay(ATAC_data_seurat), output.col.name = "MMcell.ATAC",maxRank = 10000, ncores=6)

Computing UCell scores for signatures...

Running scGate on level 1...
scGate: Detected 28568 non-pure cells at level 1

### Detected a total of 28568 non-pure cells for selected signatures - 29.34% cells marked for removal (active.ident)

Thanks

**Comment by mass-a** [comment]
Hello again,
we have some guidelines for the analysis of scATAC-seq in [this vignette](https://carmonalab.github.io/scGate.demo/scGate.ATAC-seq.html), including how to choose a reasonable `maxRank` parameter.

A useful diagnostic tool is the function `scGate::plot_UCell_scores()`, which allows you to visualize the distribution of scores for all evaluated signatures. This can tell you whether your signatures can detect the target population, and whether you may have to adjust the thresholds for positive and negative signatures (`pos.thr` and `neg.thr`). If this question is related to the other issue you submitted, you may also want to specify multiple "positive" signatures if your target population is defined by mutually exclusive markers :)

Best
-m
